spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/surldb
    username: surl
    password: surlAdmin
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true